# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout pyAGA
      uses: actions/checkout@v3
      with:
        path: pyAGA/
    - name: Checkout SCIP 7.0.3
      uses: actions/checkout@v3
      with:
        path: scip/
        repository: scipopt/scip
        ref: refs/tags/v703
    - name: Checkout PaPILO 1.0.2
      uses: actions/checkout@v3
      with:
        path: papilo/
        repository: scipopt/papilo
        ref: refs/tags/v1.0.2
    - name: Checkout SoPlex 5.0.2
      uses: actions/checkout@v3
      with:
        path: soplex/
        repository: scipopt/soplex
        ref: refs/tags/release-502
    - name: Checkout bliss
      uses: actions/checkout@v3
      with:
        path: bliss/
        repository: ds4dm/bliss
        ref: refs/tags/v0.73.3
    - name: Build an install bliss
      run: |
        cd bliss
        cmake .
        make
        sudo make install
        cd ..
    - name: ls
      run: ls
    - name: Install C++ Boost (needed for PaPILO)
      run: sudo apt-get install libboost-all-dev  
    - name: Build PaPILO
      run: |      
        cd papilo
        cmake .
        make
        sudo make install
        cd ..
    - name: Build SoPlex
      run: |
        cd soplex
        cmake .
        make
        sudo make install
        cd ..
    - name: Build SCIP
      run: |                                                              
        cd scip
        cmake -DZIMPL=off -DIPOPT=off .
        make
        sudo make install
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f pyAGA/requirements.txt ]; then pip install -r pyAGA/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        cd pyAGA/
        python -m unittest test_short.py
