# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
    # installation directory for scip
    SCIP_INSTALL_PREFIX: ${{ github.workspace }}/install

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pyAGA
      uses: actions/checkout@v3
      with:
        path: pyAGA/

    - name: Restore SCIP and dependencies from cache, if available
      id: restore_cache
      uses: actions/cache@v3
      with:
        path: ${{ env.SCIP_INSTALL_PREFIX }}
        key: ${{ runner.os }}-build_scip_cache_5

    - name: Build SCIP 7.0.3 and dependencies
      if: steps.restore_cache.outputs.cache-hit != 'true'
      uses: ./pyAGA/.github/actions/build_scip
      with:
        install-prefix: ${{ env.SCIP_INSTALL_PREFIX }}

    - name: Add all programs to path
      run: echo "${{ env.SCIP_INSTALL_PREFIX }}/bin" >> $GITHUB_PATH

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f pyAGA/requirements.txt ]; then pip install -r pyAGA/requirements.txt; fi

    - name: Test with unittest
      run: |
        pushd pyAGA/
        python -m unittest
        popd
